spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/intensity
    username: intensity
    password: intensity
  jpa:
    show-sql: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
